[tool.poetry]
name = "task-list"
version = "1.0.0"
description = ""
authors = ["Chris Lin <chris.ci.lin@viewsonic.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pytest = "^8.3.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
